#!/bin/bash
cd "$(dirname $(readlink -f $0))"

PIDS=$(pgrep -d" " "$(basename $0)");
for PID in $PIDS
do
        [[ "$PID" -ne "$$" ]] && kill -9 -"$PID";
done
#mplayer_opts="-quiet -really-quiet -ao alsa:device=hw=1.0 -vo null -vc null"
cvlc_opts=" -q --clock-jitter=0 --aout alsa --no-video -Idummy --alsa-audio-device hw:1"
play="$@"
if [ -z "$play" ]; then play="http://localhost:1976/ckradio1.m3u"; fi;
cvlc "$play" $cvlc_opts
#mplayer $mplayer_opts "$play"
