#!/bin/bash
cd "$(dirname $(readlink -f $0))"
pidfile="/tmp/fmtx.pid"
if [ -f "$pidfile" ]; then
        pid=$(cat ${pidfile});
	kill -0 $pid
	if [ "$?" -eq "0" ]; then kill -15 $pid; fi;
fi;
echo $$>${pidfile};

cvlc_opts=" -q --clock-jitter=0 --aout alsa --no-video -Idummy --alsa-audio-device hw:1"

play="$1"
if [ -z "$play" ]; then play="http://localhost:1976/ckradio1.m3u"; fi;


killall cvlc
killall vlc

case "$play" in
        #wfmu) cvlc  http $cvlc_opts
	#;;
	null) sleep 1
	;;
	*) cvlc $play $cvlc_opts
	;;
esac
rm $pidfile;
#mplayer -quiet -really-quiet -ao alsa:device=hw=1.0 -vo null -vc null $@
