#!/bin/bash
pipe="/tmp/ckradio"


PIDS=$(pgrep -d" " "$(basename $0)");
for PID in $PIDS
do
        [[ "$PID" -ne "$$" ]] && kill -9 -"$PID";
done

if [[ ! -p $pipe ]]; then
   exit 1;
   # mkfifo $pipe
fi

while [ -p $pipe ]
do
	cat $pipe | ices /etc/ices2/ices-ckradio1.xml
	sleep 2
done

