#!/bin/bash
IC_USER=""
IC_PASS=""
IC_HOST=""
IC_PORT=""
IC_MOUNT=""
source ${HOME}/.icecast
title=$(echo "$@" | sed -e 's/ /+/g');
sleep 120
curl "http://${IC_USER}:${IC_PASS}@${IC_HOST}:${IC_PORT}/admin/metadata?song=${title}&mount=/${IC_MOUNT}&mode=updinfo&charset=UTF-8" > /dev/null 2>&1;
